### PR TITLE
Changes to support ADFS/WS-Federation SAML2.0

### PR DESCRIPTION
**Pull request by sandeep048**
Fixed to ensure tests are all passing.

### CODE REVIEW

**Comment by pitbulk** [comment]
Why create a new PR, when I already closed https://github.com/onelogin/python-saml/pull/126 ?

**Comment by sandeep048** [comment]
I created a new PR since the previous one had failing tests. I updated some comments in #126. Please have a look. Thanks.

**Comment by sandeep048** [comment]
Did you guys do any testing with WS-Fed/ Microsoft Secure Token Service (SAML2.0)??

**Comment by pitbulk** [comment]
Yes, we did.

**Comment by pitbulk** [comment]
The toolkit currently supports ADFS/WS-Federation and don't need proposed changes.

**Pull request closed without merging**
