### PR TITLE
Get/validate assertion when empty Response signature ref URI

### PR DESCRIPTION
**Pull request by toopy**
In this PR we update the assertion filtering and validation when the Response signature reference URI is empty  (cf. #108):

1. we allow the assertion filtering by doing an already accepted fallback on the main Response node (Cf.: dab3aba99b99fc7234dbafaeffb02338ed59d5bc)
2. we do not modify the signature reference URI when we validate the xml content with the IdP certificate (Cf.: feedae7b2b86d7bc7f5f1016210caac594b9dcfe)

### CODE REVIEW

**Comment by pitbulk** [comment]
Thanks for contribute.

I will need to review it and check for security implications.

**Comment by toopy** [comment]
Just rebased ;)

**Comment by toopy** [comment]
Rebased!

**Comment by pitbulk** [comment]
I merged this PR, but after reading the core specs ad review what was merged I have doubts.

I understand point 2). Test pass because you are not manipulating the URI value, but don't know why this is done only for this specific case.

At spec I read

```
5.4.2 References
SAML assertions and protocol messages MUST supply a value for the ID attribute on the root 
element of the assertion or protocol message being signed. The assertion’s or protocol message's 
root element may or may not be the root element of the actual XML document containing the signed 
assertion or protocol message (e.g., it might be contained within a SOAP envelope).

Signatures MUST contain a single <ds:Reference> containing a same-document reference to the ID
attribute value of the root element of the assertion or protocol message being signed. For example, 
if the ID attribute value is "foo", then the URI attribute in the <ds:Reference> element MUST be "#foo".
```

**Comment by toopy** [comment]
No idea. Sorry I did see this specification. I send this PR according a *personal* case. I just deduce the new behavior from the existing else/if test. May be I am wrong, but I do not think I introduced something that was not there.

According the specification may be we should be more strict (or optionally more strict) and not allow `final_query = "/samlp:Response"` at all.

**Comment by pitbulk** [comment]
I think I may remove the part when I modify manually the URI, but I will need more time to read specs and other implementations.

**Pull request merged**
