### PR TITLE
Get nameid when element decrypted twice

### PR DESCRIPTION
**Pull request by toopy**
After adding tests in our project we figured out that `nameids` could not be decrypted due to a small error. When getting the `nameid` and `nameid_data` we call `decrypt_element` twice with an `etree._Element`. The first time the node is decrypted in place, then the decryption method fail on the second call.

Additionally it looks like testing keys are equivalent and tests on the method should not fail because of the keys.

In this PR we add an option to decrypt an element in place or copy it before decryption.

### CODE REVIEW

**Comment by pitbulk** [comment]
It looks good, let me some days to execute some more tests.

**Comment by toopy** [comment]
UP

**Comment by pitbulk** [comment]
Sorry for the delay, I will test and merge yours PRs today.

**Comment by toopy** [comment]
No emergency, just a small reminder here ;)

**Pull request merged**
