### PR TITLE
Docs for OS X installation of libsecxml1

### PR DESCRIPTION
**Pull request by AvnerCohen**

### CODE REVIEW

**Comment by pitbulk** [comment]
libsecxml1 dependence was already mentioned
https://github.com/onelogin/python-saml/blob/master/README.md#dependences


And I don't think is necessary to mention the brew command...

**Comment by AvnerCohen** [comment]
Could be, this means an OS X user of the library needs to spend some time finding that out from this list of dependencies? Do you see any harm in providing the extra information?
I for one spent some time on that and to me, as an OS X user, this could of been very beneficial.

**Comment by pitbulk** [comment]
Ok, but I don't think libsecxml1 is the unique dependence, what about dm.xmlsec.binding?

If you want to provide full documentation about how to install python-saml on OSX I can host that specific info at the repo, but need to be complete.

**Comment by AvnerCohen** [comment]
This seems to work out of the box with the combination of the python lib in the setup.py and the dependencies of the brew formula:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/libxmlsec1.rb

To me, once running the formula, it worked. I might be missing something though, I have little knowledge of the ins of SAML.

**Comment by pitbulk** [comment]
In order to check that all is installed as expected, try to deploy any demo and let me know if the SAML flow. Or install the dev dependencies
```
pip install -e ".[test]"
``` 
and execute the tests:
```
python setup.py test
```

**Comment by AvnerCohen** [comment]
Good idea, this seems to work just fine.
Here is the full log of the install + tests for reference:

https://gist.github.com/AvnerCohen/d334c7680458e79a7c9906175527aaea

**Pull request merged**
