### PR TITLE
Allow empty nameid if setting wantNameId is false

### PR DESCRIPTION
**Pull request by toopy**
We encounter a case were the IdP send us back a response with an empty NameID node. For now and we have to validate its response with the setting `strict` set to `false`.

In this PR we would to allow this case more explicitly and more in a more secure way by using the setting `wantNameId`.

### CODE REVIEW

**Comment by pitbulk** [comment]
Can you add more unit tests?

**Comment by toopy** [comment]
It should be better now ;)

**Comment by toopy** [comment]
UP

**Comment by pitbulk** [comment]
Sorry for the delay.

I finally implemented a similar behaviour here, that only raises exception when strict is enabled: https://github.com/onelogin/python-saml/commit/30cbe7c056f9e2a3892b3c61f79ac9086aa0631e

**Pull request closed without merging**
