### PR TITLE
Add hooks to retrieve last-sent and last-received requests and responses

### PR DESCRIPTION
**Pull request by haikuginger**
To get more data for troubleshooting in production, we've added hooks to allow us to pull the relevant XML documents out of `python-saml` for logging on our side of things. This way, we can retest those documents on a non-production system to determine what might have gone wrong.

### CODE REVIEW

**Comment by pitbulk** [comment]
But why you don't collect the requests/responses that gonna be processed in the views that uses the python-saml toolkit?

**Comment by haikuginger** [comment]
In the case of responses, they can contain encrypted assertions that cannot be effectively extracted without duplicating a large amount of `python-saml`'s functionality. In both cases, requests and responses may be b64encoded, which is another layer of obfuscation.

While these concerns may be overcome with enough time spent on them, `python-saml` already takes these items into consideration as part of its standard operation; the code to get what we want already largely exists.

Oh, and I should note that we've been seeing Travis segfaults while working on this, but tests do pass locally.

**Comment by pitbulk** [comment]
it does not pass pep8/pyflakes.

**Comment by haikuginger** [comment]
Thanks for pointing that out @pitbulk; I've fixed those issues.

**Comment by haikuginger** [comment]
Rebased from [`ea8ee6`](https://github.com/open-craft/python-saml/commits/ea8ee66900fbd99b2d6d0858efb55bc5b407d294).

**Comment by haikuginger** [comment]
@pitbulk, as with the other PR I have open here, we've been using this code for a while in production, and are hoping to get it reviewed and merged here so that we can return to using the canonical source.

**Comment by pitbulk** [comment]
I think that feature makes sense, but I was busy with a security improvement that I'm publishing today with a new release. I was so busy with that, since I mad this improvements in all the toolkits.

I think next eeek I will be able to review and add this functionality and maybe do a minor release with it.

**Comment by pitbulk** [comment]
This PR covers:
- Last SAMLResponse processed by process_response
- Last SAMLRequest sent by login

 But what happens with:
- Last SAMLRequest sent by logout
- Last SAMLRequest processed by process_slo
- Last SAMLResponse processed by process_slo
- Last SAMLRequest sent by process_slo
- Last SAMLResponse sent by process_slo

**Comment by haikuginger** [comment]
@pitbulk, our what our organization needs is just the login request and the response received. I can look into whether we can expand our scope on this to cover those items in a subsequent PR, but for right now, we'd like to get this piece merged.

**Comment by bradenmacdonald** [comment]
@pitbulk Hi :) @haikuginger is working with me on this. We want to have something you can merge, so please let us know what you'd need for that to happen. To answer your question, currently the last SAML request from those other processes is not saved. If you it's important to have that consistency in place before this can be merged, let us know.

**Comment by pitbulk** [comment]
It's ok, I will improve your PR and merge it soon.

**Comment by pitbulk** [comment]
@bradenmacdonald , @haikuginger 

I improved the PR here: https://github.com/onelogin/python-saml/pull/171

It lacks some tests, but I will implement them today and if you agree with the solution, merge it to master.

**Comment by pitbulk** [comment]
PR #171 is ready, @bradenmacdonald , @haikuginger can you review?

**Comment by pitbulk** [comment]
#171 is ready, @bradenmacdonald , @haikuginger can you review?

**Pull request merged**
